{{- if and .Values.cnpg.enabled (not .Values.cnpg.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitorama-demo.cnpgAppSecretName" . }}
  labels:
    app.kubernetes.io/name: cnpg
    {{- include "monitorama-demo.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.database.user | quote }}
  password: {{ .Values.cnpg.database.password | quote }}
{{- end }}
