{{- if .Values.spaceWeather.weatherApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitorama-demo.fullname" . }}-weather-api
  labels:
    app.kubernetes.io/name: space-weather
    {{- include "monitorama-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  WEATHER_API_KEY: {{ .Values.spaceWeather.weatherApiKey | quote }}
{{- end }}
