apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitorama-demo.fullname" . }}-basic-otel
  labels:
    app.kubernetes.io/name: basic-otel
    {{- include "monitorama-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.basicOtel.service.type }}
  selector:
    app.kubernetes.io/name: basic-otel
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.basicOtel.service.port }}
      targetPort: http
