# Generated by Django 5.0.6 on 2024-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacedir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='api_uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
